### ISSUE TITLE
Report Feature Bugs

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#202]
#### Can't update project title 

You are only able to update the reporting feature title once. If you click back into it, it doesn't update.

![image](https://user-images.githubusercontent.com/13791320/59880485-bf817d00-9372-11e9-8678-f2a90a856035.png)

#### Saved Map Settings Don't Affect Parcel Layer

The parcel layer isn't affected by saved settings. If a user has it on, it stays on even if a user selects a report setting that doesn't include it. If a report setting is supposed to include it, it doesn't turn on when that setting is selected.

**Comment by eanderson4** [comment]
These should both be fixed in next update

**Comment by jakebanderson321** [comment]
Looks good. 

However, now Parcel layer still shows lines, even once it's been toggled off.

![image](https://user-images.githubusercontent.com/13791320/60116305-64b69f80-973d-11e9-9af4-c66803b3a074.png)

**Comment by eanderson4** [comment]
I'm guessing this was resolved, feel free to reopen if stil an issue
